coverage:
  range: 70..90
  round: down
  precision: 2
  status:
    project: off
    patch: off

fixes:
  - "/home/runner/work/nndt/nndt/::"

ignore:
  - "setup.py"
  - "__init__.py"
  - "tests/*.py"