name: CI-test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

    - name: Install pytest
      run: pip install pytest

    - name: Install requirements
      run: python setup.py install

    - name: Run unit tests
      run: pytest tests/*