name: CI-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codecov:

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Caching python modules
      - uses: actions/cache@v2
        id: cache-venv 
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Code style fixing
        run: |
          pip install black
          black --target-version=py310 .
      
      - name: Prepare patient data
        run: 7z x tests/acdc_for_test.7z

      - run: python -m venv ./.venv && . ./.venv/bin/activate && 
             pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: |
          pip install pytest
          pip install pytest-cov
          . ./.venv/bin/activate && pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
