name: CI-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codecov:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Code style fixing
        run: |
          pip install black
          black --target-version=py310 .

      - name: Test requirements installation
        run: python setup.py install

      - name: Prepare patient data
        run: 7z x tests/acdc_for_test.7z

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests