name: ci-workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Cache python modules
        uses: actions/cache@master
        id: cache-modules
        with:
          path: ./.venv/
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          python -m venv ./.venv
          . ./.venv/bin/activate
          python setup.py install

      - name: Check code style
        run: |
          . ./.venv/bin/activate
          pip install black black[jupyter]
          black --check .

      - name: Unpack testing data
        run: |
          . ./.venv/bin/activate
          7z x tests/acdc_for_test.7z

      - name: Generate coverage report
        run: |
          . ./.venv/bin/activate
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.xml
      #     flags: unittests

      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/${{ matrix.os }}/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}